version: "3.5"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys
    environment:
      - HOME=/root
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
